import { useEffect, useState } from "react";
import axios from "axios";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { List } from "antd";
import { DragDropContext, Droppable, Draggable } from "react-beautiful-dnd";

const Home = () => {
	const [apis, setApis] = useState([
		{
			id_pattern: "",
			pattern: "",
			priority: ""
		}
	]);
	useEffect(() => {
		fetchData();
	}, []);

	const fetchData = async () => {
		try {
			const { data } = await axios.get(
				"https://api.livebutler.io/v2/ai-patterns"
			);
			console.log(data);
			setApis(data);
		} catch (error) {
			console.log(error);
		}
	};
	// const reorder = (apis, startIndex, endIndex) => {
	// 	const result = Array.from(apis);
	// 	const [remove] = result.splice(startIndex, 1);
	// 	result.splice(endIndex, 0, remove);

	// 	return result;
	// };

	const onEnd = result => {
		const { destination, source, reason } = result;

		if (!destination || reason === "CANCEL") return;

		if (
			destination.droppableId === source.droppableId &&
			destination.index === source.index
		) {
			return;
		}
		const datas = Object.assign([], apis);
		const droppedDatas = apis[source.index];

		datas.splice(source.index, 1);
		datas.splice(destination.index, 0, droppedDatas);

		setApis(datas);

		console.log(result);

		// setApis(reorder(apis, result.source.index, result.destination.index));
	};

	// const saveData = async () => {
	// 	try {
	// 		const { data } = await axios.put(
	// 			"https://api.livebutler.io/v2/ai-patterns"
	// 		);
	// 		console.log(data);
	// 		setApis(data);
	// 		window.localStorage.setItem("data", JSON.stringify(data));
	// 	} catch (error) {
	// 		console.log(error);
	// 	}
	// };

	// let data = [apis];

	return (
		<div className={styles.container}>
			<Head>
				<title>Live Butler</title>
				{/* <meta name='description' content='Generated by create next app' /> */}
				{/* <link rel='icon' href='/favicon.ico' />/ */}
			</Head>
			<button className='btn btn-primary m-4' onClick={fetchData}>
				Get Live Butler Data
			</button>
			<div className='structure'>
				<ul className='data-structure'>
					<li>Number</li>
					<li>Id</li>
					<li>Key Words</li>
				</ul>
			</div>
			<div className='content'>
				<DragDropContext onDragEnd={onEnd}>
					<Droppable droppableId='dp1'>
						{(provided, snapshot) => (
							<div ref={provided.innerRef} {...provided.droppableProps}>
								{apis.map((item, index) => (
									<Draggable
										draggableId={item.id_pattern}
										key={item.id_pattern}
										index={index}
									>
										{(provided, snapshot) => (
											<div
												ref={provided.innerRef}
												{...provided.draggableProps}
												{...provided.dragHandleProps}
											>
												{/* <div>{index + 1}</div> */}
												<ul
													style={{ border: " 1px solid black" }}
													className='margin'
													draggable

													// on={handleDrag && handleDrop}
												>
													<div>{index}</div>
													<div>{item.id_pattern}</div>
													<div>{item.pattern}</div>
												</ul>
											</div>
										)}
									</Draggable>
								))}
								{provided.placeholder}
							</div>
						)}
					</Droppable>
				</DragDropContext>
			</div>
			{/* <button className='btn btn-primary m-4' onClick={saveData}>
				Save Live Butler Data
			</button> */}
			{/* <pre>{JSON.stringify(apis, null, 4)}</pre> */}
		</div>
	);
};

export default Home;
